server:
  port: 0

spring:
  application:
    name: x-hall

# 节点配置：HALL 类型
x:
  cluster:
    type: HALL
    name: hall-1
    weight: 1
    message-types: [2000]
    message-pkgs:
      - de.kseek.core.message
      - de.kseek.hall.message
    tcp-address:
      host: 127.0.0.1
      port: 30003
  zookeeper:
    x-root: x-game
    connects: 127.0.0.1:2181
    base-sleep-time-ms: 1000
    max-retries: 3
    session-timeout-ms: 10000
    connection-timeout-ms: 3000
