server:
  port: 0
  servlet:
    context-path: /api

spring:
  application:
    name: x-login
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/x-login
      # 无本地 MongoDB 时可改为远程或注释后使用内存/测试配置

# 节点配置：ACCOUNT 类型
x:
  cluster:
    type: ACCOUNT
    name: login-1
    weight: 1
    message-types: [1000]
    message-pkgs:
      - de.kseek.core.message
      - de.kseek.login.message
    tcp-address:
      host: 127.0.0.1
      port: 30001
  zookeeper:
    x-root: x-game
    connects: 127.0.0.1:2181
    base-sleep-time-ms: 1000
    max-retries: 3
    session-timeout-ms: 10000
    connection-timeout-ms: 3000
